apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: ghcr.io/loki-afro/argocd/spring-petclinic:main
        imagePullPolicy: Always
        name: spring-petclinic
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: configmap
          - secretRef:
              name: secret

