name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: "Loki-Afro"
          password: ${{ secrets.GH_REGISTRY_SECRET }}
          repository: loki-afro/argocd/spring-petclinic
          tags: main
